mlcommons/logging

- .gitignore
- README.md
- mllog/README.md
- mllog/__init__.py
- mllog/constants.py
- mllog/examples/__init__.py
- mllog/examples/dummy_example.py
- mllog/mllog.py
- mllog/test_mllog.py
- setup.py
Add mllog package, adapted from mlperf/training
> Add initial code

- mlperf_logging/mllog/README.md
small fix after lib reorganization
> update mllog README after moving to mlperf_logging library

- mlperf_logging/mllog/mllog.py
- Add an encoder for certain numpy types
- No longer attempt to cast all values to float
Fixes #7
> Improve JSON encoding

- mlperf_logging/compliance_checker/0.7.0/common.yaml
- mlperf_logging/compliance_checker/0.7.0/resnet.yaml
- mlperf_logging/compliance_checker/0.7.0/resnet_lars.yaml
- mlperf_logging/compliance_checker/0.7.0/resnet_sgd.yaml
- mlperf_logging/compliance_checker/0.7.0/ssd.yaml
- mlperf_logging/compliance_checker/mlp_compliance.py
Changes:
* fixes multiple tests handling in END rule
* reorganize RN rules, to make an output clearer
* epoch_train/block_samples are optional
> Compliance checker update

- mlperf_logging/compliance_checker/__main__.py
- mlperf_logging/compliance_checker/mlp_compliance.py
- mlperf_logging/package_checker/README.md
- mlperf_logging/package_checker/__main__.py
- mlperf_logging/package_checker/package_checker.py
> Package checker

- mlperf_logging/package_checker/package_checker.py
- mlperf_logging/result_summarizer/result_summarizer.py
- verify_for_v0.7_training.sh
This fixes a few bugs in package checking, including updating it for the the newest log format. Also adds a utility for people to use.
This also includes converting form the millisecond timestamps now used in the new logs.
> Fix logging

- mlperf_logging/compliance_checker/0.7.0/common.yaml
Adding the "preview" status which is listed in the submission rules here: https://github.com/mlperf/policies/blob/master/submission_rules.adoc#73-results-categories
> Adding "preview" Status.

- mlperf_logging/result_summarizer/result_summarizer.py
See my email summarizing this issue. This is the PR I will use for summarizing the initial results.
> Fix counting processors and accelerations in results summarizer.

- mlperf_logging/system_desc_checker/system_desc_checker.py
> [system_desc_checker] fix 'divison' typo

- log_parsers/README.md
- log_parsers/parse_mlperf.py
parse_mlperf.py - v5.2
README.md - Reflects v5
> Updated parser script and readme

- mlperf_logging/result_summarizer/result_summarizer.py
Added an extra optional command line argument to run the printed rows out to a csv.
I've put the headers inline, so that if the fields are added/removed, it is hopefully more obvious that a header needs changing too. If this is better structured differently, then happy to change.
Many Thanks,
> Writing the results to csv file

- mlperf_logging/rcp_checker/training_1.0.0/rcps_resnet.json
> [RCP][ResNet] Add bn_span.

- mlperf_logging/result_summarizer/README.md
> [README] Update result summarizer's readme.

- mlperf_logging/compliance_checker/hpc_1.0.0/open_common.yaml
I have added an open_common.yaml file for hpc-1.0
> added open_common.yaml

- setup.py
> [pip] Include pyyaml, numpy and scipy as dependencies in setup.py.

- mlperf_logging/rcp_checker/hpc_1.0.0/rcps_cosmoflow.json
Hi, I'm a submitter at Fujitsu.
This PR adds a new cosmoflow RCP for batch size 512.
It enables our submitted results to pass the package checker.
Thanks,  
Akihiro
> [HPC][RCP][Cosmoflow] Update cosmoflow RCPs for bs=512

- mlperf_logging/rcp_checker/training_1.1.0/rcps_bert.json
> [BERT] BS4096 RCP

- mlperf_logging/compliance_checker/training_1.1.0/closed_bert.yaml
This solves issue https://github.com/mlcommons/logging/issues/204
> Removed non-existing tensor from weight initialization list

- mlperf_logging/compliance_checker/mlp_compliance.py
> Fail checker if there are weight initialization mismatches.

- mlperf_logging/rcp_checker/training_2.0.0/rcps_bert.json
> [BERT] BS4608 RCP using HP set provided by GraphCore

- mlperf_logging/result_summarizer/result_summarizer.py
> Fix details link

- mlperf_logging/rcp_checker/rcp_checker.py
Fix #251 
@relja128 @xyhuang @ckt624
> Fix _prune_rcps for HPC

- mlperf_logging/benchmark_meta.py
- mlperf_logging/compliance_checker/hpc_2.0.0/closed_common.yaml
- mlperf_logging/compliance_checker/hpc_2.0.0/closed_cosmoflow.yaml
- mlperf_logging/compliance_checker/hpc_2.0.0/closed_deepcam.yaml
- mlperf_logging/compliance_checker/hpc_2.0.0/closed_deepcam_cosine_annealing.yaml
- mlperf_logging/compliance_checker/hpc_2.0.0/closed_deepcam_lamb.yaml
- mlperf_logging/compliance_checker/hpc_2.0.0/closed_deepcam_multistep.yaml
- mlperf_logging/compliance_checker/hpc_2.0.0/closed_oc20.yaml
- mlperf_logging/compliance_checker/hpc_2.0.0/common.yaml
- mlperf_logging/compliance_checker/hpc_2.0.0/open_common.yaml
- mlperf_logging/compliance_checker/hpc_2.0.0/open_cosmoflow.yaml
- mlperf_logging/compliance_checker/hpc_2.0.0/open_deepcam.yaml
- mlperf_logging/compliance_checker/hpc_2.0.0/open_oc20.yaml
- mlperf_logging/rcp_checker/hpc_2.0.0/rcps_cosmoflow.json
- mlperf_logging/rcp_checker/hpc_2.0.0/rcps_deepcam.json
- mlperf_logging/rcp_checker/hpc_2.0.0/rcps_oc20.json
- mlperf_logging/repo_checker/repo_checker.py
- scripts/verify_for_v2.0_hpc.sh
@memani1 @sparticlesteve Add config for hpc 2.0.0 based on 1.0.0 config. The idea would be to use this as a starting point and make the specific modifications needed. This PR includes:
- Initial stuff for hpc 2.0
- Script to run submission checker compatible with the UI (based on the one of training v2.0)
> Add hpc 2.0.0 config

- mlperf_logging/result_summarizer/result_summarizer.py
Partly solve issue #258. Sorting the summary as requested in this [comment](https://github.com/mlcommons/logging/issues/258#issuecomment-1230989494)
> Sort results

- mlperf_logging/rcp_checker/hpc_2.0.0/rcps_cosmoflow.json
- mlperf_logging/rcp_checker/hpc_2.0.0/rcps_deepcam.json
> Update HPC RCPs

- mlperf_logging/rcp_checker/training_2.1.0/rcps_ssd.json
Update to RCPs for training 2.1 submission
- RetinaNet
> Training 2.1 RCPs

- mlperf_logging/rcp_checker/rcp_checker.py
Add an option to allow user to specify a custom RCP file.
> Custom RCP

- mlperf_logging/result_summarizer/result_summarizer.py
- mlperf_logging/result_summarizer/xlsx_config.yaml
> Output summary in .xlsx format

- mlperf_logging/rcp_checker/rcp_checker.py
> Default value for rcp_score_norm

- mlperf_logging/result_summarizer/result_summarizer.py
Only read xlsx config when flag is passed. This was making the UI to crash because the config file was not there
> Fix result summarizer xlsx-UI interation

- mlperf_logging/rcp_checker/training_3.0.0/rcps_dlrm_dcnv2.json
Update to dlrm_dcnv2 RCPs for training 3.0 submission
> [DLRM_DCNV2] Training v3.0 RCPs

- mlperf_logging/compliance_checker/mlp_compliance.py
Quick fix:
- `if v['REQ'].startswith('AT_LEAST')` condition was passing in unexpected cases
> [URGENT] Fix AT_LEAST checks

- mlperf_logging/compliance_checker/training_3.1.0/common.yaml
Please merge this today - URGENT
> replacing ^ with | in common.yaml to fix last minute change in SD logs

- mlperf_logging/result_summarizer/result_summarizer.py
Fix this [issue](https://github.com/mlcommons/submissions_training_power_v3.1/issues/2).
> Fix Bug: Use unsorted scores to create index

- mlperf_logging/result_summarizer/result_summarizer.py
> Add node count to summary

- mlperf_logging/result_summarizer/result_summarizer.py
> Add perf metric to power summary

- mlperf_logging/rcp_checker/rcp_checker.py
This change restores backward compatibility for the `3.1.0` ruleset for the `stable-diffusion` benchmark.
> [RCP-checker][SD] 3.1.0 compablity fix

- mlperf_logging/benchmark_meta.py
- mlperf_logging/compliance_checker/README.md
- mlperf_logging/compliance_checker/mlp_parser/__init__.py
- mlperf_logging/compliance_checker/mlp_parser/ruleset_410.py
- mlperf_logging/compliance_checker/training_4.1.0/closed_bert.yaml
- mlperf_logging/compliance_checker/training_4.1.0/closed_common.yaml
- mlperf_logging/compliance_checker/training_4.1.0/closed_dlrm_dcnv2.yaml
- mlperf_logging/compliance_checker/training_4.1.0/closed_gnn.yaml
- mlperf_logging/compliance_checker/training_4.1.0/closed_gpt3.yaml
- mlperf_logging/compliance_checker/training_4.1.0/closed_llama2_70b_lora.yaml
- mlperf_logging/compliance_checker/training_4.1.0/closed_ssd.yaml
- mlperf_logging/compliance_checker/training_4.1.0/closed_stable_diffusion.yaml
- mlperf_logging/compliance_checker/training_4.1.0/common.yaml
- mlperf_logging/compliance_checker/training_4.1.0/open_bert.yaml
- mlperf_logging/compliance_checker/training_4.1.0/open_common.yaml
- mlperf_logging/compliance_checker/training_4.1.0/open_dlrm_dcnv2.yaml
- mlperf_logging/compliance_checker/training_4.1.0/open_gnn.yaml
- mlperf_logging/compliance_checker/training_4.1.0/open_gpt3.yaml
- mlperf_logging/compliance_checker/training_4.1.0/open_llama2_70b_lora.yaml
- mlperf_logging/compliance_checker/training_4.1.0/open_ssd.yaml
- mlperf_logging/compliance_checker/training_4.1.0/open_stable_diffusion.yaml
- mlperf_logging/mllog/examples/power/compute_metric_example.py
- mlperf_logging/package_checker/README.md
- mlperf_logging/rcp_checker/README.md
- mlperf_logging/repo_checker/README.md
- mlperf_logging/result_summarizer/config.yaml
Some changes slipped and were not changed in https://github.com/mlcommons/logging/pull/381
This PR fixes it. Apologies for the hassle
> Add support for compliance for 4.1

- mlperf_logging/compliance_checker/training_5.0.0/closed_llama31_405b.yaml
- mlperf_logging/compliance_checker/training_5.0.0/common.yaml
All LLMs use `samples_count` for accounting. This PR aligns the compliance check. PR to the reference repository is coming soon
> Change epoch_num to samples_count for llama31
