mlcommons/logging

mlperf_logging/compliance_checker/0.7.0/common.yaml
This updates the common checks to match our understanding of the rules:
- "seed" is optional
- You can choose between using "epoch/eval separately" or "block style". You can choose one or the other.
=> Change compliance checks to match our understanding of the rules.

mlperf_logging/mllog/mllog.py
inspect.stack() can be an extremely expensive function, adding 50ms or more for each call, depending on the stack depth and other factors.  For this potentially time-sensitive setting it's better to use the much faster inspect.currentframe() and manual back-traversal of the python frames.
=> Use a faster callstack traversal for get_caller

mlperf_logging/compliance_checker/0.7.0/minigo.yaml, mlperf_logging/compliance_checker/mlp_compliance.py
* MiniGo doesn't have a train dataset, so train samples should not be required. 
* Eval samples are covered by `eval_games`. 
* `actual_selfplay_games_per_generation` should be reported more than once (once per epoch)
=> [compliance_checker][minigo] checks update

mlperf_logging/compliance_checker/mlp_compliance.py
We used int() instead of round() resulting in correct "is integer" checking.
=> Fix integer conversion error.

mlperf_logging/compliance_checker/0.7.0/minigo.yaml
according to
https://github.com/mlperf/training_policies/blob/16302f66575f2afbaa096eba5bdc26b62918fd3f/training_rules.adoc#3-benchmarks
target is 0.5 not 0.55
=> [compliance_checker][minigo] fixing a typo in the target accuracy check

mlperf_logging/compliance_checker/mlp_compliance.py, mlperf_logging/package_checker/package_checker.py, mlperf_logging/result_summarizer/result_summarizer.py
Under olympic scoring rules, we are allowed to drop one run which does not converge. This updates the package verifier to allow submitters to submit non-converging runs as long as it following this olympic scoring rule.
=> Adjusting package verifier to support convergence dropping.

mlperf_logging/compliance_checker/0.7.0_warn/minigo.yaml
* The save_model checks are a leftover from v0.6.
* opt_base_learning_rate is repeated
* block_start/stop in common.yaml are optional if epoch_start/stop are present, overwrite is not needed
=> [compliance_checker][minig] remove broken checks

mlperf_logging/package_checker/package_checker.py
according to
https://github.com/mlperf/training_policies/blob/master/training_rules.adoc#11-benchmark-results
package_checker should expect 5 DLRM results, not 10
=> [package_checker][DLRM] expected DLRM results set to 5

mlperf_logging/compliance_checker/1.0.0/closed_rnnt.yaml
This change is to minimize confusion in the reference implementation.
More details in https://github.com/mlcommons/training/pull/461
=> [RNN-T] clarify gradient clipping status

mlperf_logging/package_checker/package_checker.py
There is a missing comma in the `_ALLOWED_BENCHMARKS_V10` list, so `rnnt` and `unet3d` are merged into a single string.
=> [package checker] add missing comma

mlperf_logging/package_checker/package_checker.py
`rcp_chk._check_directory` only return False when `rcp_bypass` is `False` and RCP checking actually failed. Thus, `WARNING` is not very accurate.
=> WARNING -> ERROR if rcp checking fails in package checker.

mlperf_logging/package_checker/package_checker.py, mlperf_logging/rcp_checker/__main__.py, mlperf_logging/rcp_checker/rcp_checker.py
Colleagues working on BERT noticed, that BERT is not reporting `num_epochs`, so they propose to use `train_samples` in RCP checker instead.
Let's discuss it on the meeting today.
=> [RCP checker] handle BERT-sepcific progress reporting

mlperf_logging/rcp_checker/rcp_checker.py
DLRM benchmark is very stable, and after dropping the fastest and the slowest result, all results are the same. As result, RCPs require a perfect match in submission. It is problematic, because epochs are reported as a floating point, and comparing floating-point numbers is error-prone.
To mitigate this issue, DLRM RCPs are rounded. However, rounding of submission epochs is missing. As result, the RCP checker rejects legal submissions.
This MR adds the missing part. Because other benchmarks report epochs as integers, this change has no impact on them.
=> [recommendation] round floating point epoch number

mlperf_logging/compliance_checker/hpc_1.0.0/closed_deepcam.yaml
@azrael417 please review this PR; in addition, could you update [HPC's DeepCam's README](https://github.com/mlcommons/hpc/tree/main/deepcam#hyperparameters) accordingly so that other submitter would know?
Thanks!
=======================================
Explanation:
In [DeepCam](https://github.com/mlcommons/hpc/tree/main/deepcam), `num_workers` is deprecated and will be replaced by `num_of_nodes` and `accelerators_per_node`. The purpose of this is to support weak scaling benchmarking in HPC: https://github.com/mlcommons/training_policies/blob/master/hpc_training_rules.adoc#62-weak-scaling-throughput
=> [Compliance][HPC][DeepCam] Replace the num_workers rule with number_of_nodes and accelerators_per_node.

mlperf_logging/rcp_checker/hpc_1.0.0/rcps_oc20.json
This PR is needed for the upcoming MLPerf HPC v1 submission deadine (Oct 8).
Previous RCP was renamed to `oc20_ref_256` to reflect the actual batch size used (not sure how I messed that up).
I reran the RCP at batch size 256 after fixing a seeding issue so that each run used a unique seed.
I have also added a new RCP for batch size 1024.
=> Update oc20 RCPs for MLPerf HPC v1

mlperf_logging/compliance_checker/hpc_1.0.0/closed_common.yaml, mlperf_logging/compliance_checker/hpc_1.0.0/closed_deepcam.yaml, mlperf_logging/result_summarizer/result_summarizer.py
This PR address #165 . If `accelerators_per_node` contains 0 in the logs, we assume that this is a pure-CPU system, and the instance scale is the `number_of_nodes`.
This PR also move the `accelerators_per_node` and `number_of_nodes` compliance check to `hpc_1.0.0/closed_common.yaml` to check those tags for all hpc benchmarks.
=> [HPC][Compliance|Result Summarizer] Allow accelerators_per_node to be 0 on pure-CPU systems.

mlperf_logging/rcp_checker/hpc_1.0.0/rcps_oc20.json, mlperf_logging/rcp_checker/rcp_checker.py
This PR enables the oc20 benchmark in the RCP checker.
It also adds a new oc20 RCP for batch size 2048.
Thank you,
Steve
=> Update oc20 RCPs

mlperf_logging/compliance_checker/__main__.py, mlperf_logging/compliance_checker/mlp_compliance.py, mlperf_logging/package_checker/package_checker.py, mlperf_logging/package_checker/seed_checker.py, mlperf_logging/rcp_checker/__main__.py, mlperf_logging/rcp_checker/rcp_checker.py, mlperf_logging/system_desc_checker/system_desc_checker.py
- Use the logging library instead of print(...) to display progress,
warnings, and errors
- Replaced almost all print(...) statements in the package, compliance,
and rcp checkers
- log outputs go to stdout and also to package_checker.log,
compliance_checker.log, rcp_checker.log, depending on what you run.
The lof iles can be changed from the command line.
- Added additional info to log outputs
- Removed exceptions/assertions at the end of the checkers when we find errors
=> Logging lib -- checker logging improvements (#180)

mlperf_logging/rcp_checker/training_2.0.0/rcps_ssd.json
The pull requests adds platform information to the SSD RCPs.
This change was requested by @emizan76  [here](https://github.com/mlcommons/logging/pull/209), and by Intel through email.
=> [SSD] updated v2.0 RCPs with platform info

mlperf_logging/result_summarizer/result_summarizer.py
This PR adds a column named `notes` into the training results, whose value is `hw_notes` + `sw_notes` from the system description json files.
I added this feature per @matthew-frank 's request. I'm not exactly sure about its context within the training submission.
=> [result_summarizer] Adding the 'notes' column.

mlperf_logging/benchmark_meta.py, mlperf_logging/rcp_checker/__main__.py, mlperf_logging/rcp_checker/rcp_checker.py, mlperf_logging/rcp_checker/training_2.0.0/rcps_ssd.json
Enable submissions with missing RCP (when the batch size of the
submission is larger than the max RCP batch size or smaller than the min
RCP batch size and convergence is faster) to be accepted with
--rcp_bypass.
Fixed json file for SSD, and added some missing 2.0.0 support.
=> Fix issue #213

mlperf_logging/repo_checker/README.md, mlperf_logging/repo_checker/__main__.py, mlperf_logging/repo_checker/repo_checker.py, scripts/verify_for_v2.0_training.sh
Added repo_checker directory and file that check whether directory tree
to be written to github hass very large files or files with
git-unfriendly names (with spaces, starting with .)
Added support to read rcp_bypass and rcp_bert_train_samples from
file package_checker_params in submission directory. This has been
added n the verify_for_v2.0_training.sh
=> Fixes for issues #205, and #224.

setup.py
Encounter an issue that pandas being installed is not capable with numpy, turns out it's because we always grab the latest pandas, and if there's an old verion numpy being install already then pip fails to fix it.
```
Traceback (most recent call last):
File "./ml_perf/train_loop.py", line 23, in <module>
import tensorflow as tf
File "/usr/local/lib/python3.8/dist-packages/tensorflow/__init__.py", line 101, in <module>
from tensorflow_core import *
File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/__init__.py", line 36, in <module>
from tensorflow._api.v1 import compat
File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/_api/v1/compat/__init__.py", line 23, in <module>
from tensorflow._api.v1.compat import v1
File …
```
=> Spedify package version in setup.py

setup.py
pandas 1.3 requires py38 which could be [too high](https://github.com/mlcommons/logging/commit/f6d428f6f3a35bffb04b0c3a7d0ea08f2264abbb#commitcomment-72311614) , lower it so it should work for py36 now.
Tested locally py36 can use up to 1.1.5. Other packages should be fine too.
=> Lower pandas version constrain to work with py36

mlperf_logging/compliance_checker/training_2.0.0/closed_minigo.yaml
This is a proposal to skip weight init. check just for minigo v2.0 submission. @emizan76 FYI, @johntran-nv already discussed with @petermattson about this requirement change, but this will probably be brought up in the training WG meeting as well.
=> [Compliance] Skipping weight init. check for minigo in v2.0 training submission

mlperf_logging/compliance_checker/training_2.0.0/closed_maskrcnn.yaml
Together with this [PR](https://github.com/mlcommons/training_policies/compare/master...ShriyaPalsamudram:shriya-mrcnn-bugfix) to change the training policy for small batch size for mrcnn
=> [MRCNN] allow lr 0.01 for when gbs < 16

mlperf_logging/compliance_checker/mlp_compliance.py
Fix #242.
Only check the `submission_*` lines once per file. The submission UI will be used for the next HPC round, so ideally we could fix this issue by then.
@emizan76 Is this safe to do?
=> Process submission logs only once

mlperf_logging/package_checker/package_checker.py, mlperf_logging/rcp_checker/rcp_checker.py
Implements rule from PR [#503](https://github.com/mlcommons/training_policies/pull/503/files#diff-7f40dc8339752524c530b449806bdd880ed3dc21d2e43c220193b6660f316434R491) in training_policies repo.
Resolves #272 
- Prints normalization factor in RCP checker if not equal to 1.0
- Sets scaling.json file in results folder if score should be scaled
=> Normalize score if submission converges faster

mlperf_logging/rcp_checker/training_2.0.0/rcps_bert.json, mlperf_logging/rcp_checker/training_2.0.0/rcps_maskrcnn.json, mlperf_logging/rcp_checker/training_2.0.0/rcps_resnet.json, mlperf_logging/rcp_checker/training_2.1.0/rcps_bert.json, mlperf_logging/rcp_checker/training_2.1.0/rcps_maskrcnn.json, mlperf_logging/rcp_checker/training_2.1.0/rcps_resnet.json
This PR: [https://github.com/mlcommons/logging/pull/238](https://github.com/mlcommons/logging/pull/238) from Training 2.0 was not merged.
So this is a new PR that adds those RCPs into both the training_2.0.0 and training_2.1.0 folders.
cc @johntran-nv @pgmpablo157321
=> [RCP] Add previously unmerged Training 2.0 RCPs

mlperf_logging/package_checker/package_checker.py, mlperf_logging/rcp_checker/__main__.py, mlperf_logging/rcp_checker/rcp_checker.py
- Refactor `main` and `__main__.py` (Resolves #286)
- Rename methods (Resolves #287)
=> RCP checker refactor: interface cleanup

mlperf_logging/package_checker/package_checker.py, mlperf_logging/rcp_checker/rcp_checker.py, mlperf_logging/result_summarizer/result_summarizer.py
- Split `check_directory()` from `RCP_Checker` class
- `RCP_Checker` created for only 1 benchmark, only reads RCPs and maintains state for 1 benchmark
- `RCP_Checker` state and stats computed (`compute_rcp_stats()`) at initialization
- `check_directory()` creates a checker with benchmark read from `get_submission_epochs()`
To check a results directory, now only need to call `check_directory()`
Depends #289 , #293
=> RCP checker refactor: load one benchmark

mlperf_logging/rcp_checker/training_3.0.0/rcps_dlrmv2.json
I'm adding initial RCPs data for the new recommender DLRMv2 benchmark for MLPerf Training v3.0.0.
1. Command to generate the data is:
```shell
GLOBAL_BATCH_SIZE=102400
LEARNING_RATE=0.004
TOTAL_TRAINING_SAMPLES=4195197692
NUM_EMBEDDINGS=40000000,39060,17295,7424,20265,3,7122,1543,63,40000000,3067956,405282,10,2209,11938,155,4,976,14,40000000,40000000,40000000,590152,12973,108,36
WORLD_SIZE=8
NUM_EVAL=20
torchx run -s local_cwd dist.ddp -j 1x8 --script dlrm_main.py -- \
--synthetic_multi_hot_criteo_path /data \
--mmap_mode \
--pin_memory \
--epochs 1 \
--embedding_dim 128 \
--dense_arch_layer_sizes 512,256,128 \
--over_arch_layer_sizes 1024,1024,512,256,1 \
--interaction_type dcn \
--dcn_num_layers 3 \
--dcn_low_rank_dim 512 \
--validation_freq_within_epoch $((TOTAL_TRAINING_SAMPLES / …
```
=> [DLRMv2] RCP for BS=102400

mlperf_logging/package_checker/package_checker.py, mlperf_logging/rcp_checker/rcp_checker.py
`_eval_submission_record` and `check_directory` return the score normalization factor for use in other python scripts/modules.
This return value is ignored in the package checker and rcp checker `main` calls to `check_directory`.
=> Make score normalization factor available in module

mlperf_logging/rcp_checker/rcp_checker.py, mlperf_logging/rcp_checker/training_3.0.0/rcps_dlrmv2.json
I'm adding extra RCPs data for the new recommender DLRMv2 benchmark for MLPerf Training v3.0.0.
1. Command to generate the data:
```
GLOBAL_BATCH_SIZE=32768  # or 65536
LEARNING_RATE=0.004
TOTAL_TRAINING_SAMPLES=4195197692
NUM_EMBEDDINGS=40000000,39060,17295,7424,20265,3,7122,1543,63,40000000,3067956,405282,10,2209,11938,155,4,976,14,40000000,40000000,40000000,590152,12973,108,36
WORLD_SIZE=8
NUM_EVAL=20
torchx run -s local_cwd dist.ddp -j 1x8 --script dlrm_main.py -- \
--synthetic_multi_hot_criteo_path /data \
--mmap_mode \
--pin_memory \
--epochs 1 \
--embedding_dim 128 \
--dense_arch_layer_sizes 512,256,128 \
--over_arch_layer_sizes 1024,1024,512,256,1 \
--interaction_type dcn \
--dcn_num_layers 3 \
--dcn_low_rank_dim 512 \
--validation_freq_within_epoch $((TOTAL_TRAINING_SAMPLES / …
```
=> [DLRMv2] RCPs for BS=32768 and BS=65536

mlperf_logging/benchmark_meta.py, mlperf_logging/compliance_checker/README.md, mlperf_logging/compliance_checker/mlp_compliance.py, mlperf_logging/compliance_checker/mlp_parser/ruleset_310.py, mlperf_logging/compliance_checker/training_3.1.0/closed_common.yaml, mlperf_logging/compliance_checker/training_3.1.0/closed_stable_diffusion.yaml, mlperf_logging/compliance_checker/training_3.1.0/open_common.yaml, mlperf_logging/compliance_checker/training_3.1.0/open_stable_diffusion.yaml, mlperf_logging/rcp_checker/rcp_checker.py, mlperf_logging/rcp_checker/training_3.1.0/rcps_stable_diffusion.json
* compliance checker update for StableDiffusion
* RCP checker update for StableDiffusion
* renamed the stable diffusion rules files to match the benchmark name
* added "stable_diffusion" to relevant configs, renamed rcp file
=> Libraries update for Stable Diffusion (#335)

mlperf_logging/rcp_checker/rcp_checker.py
Existing check will pass on lines such as:
```
:::MLLOG {"namespace": "", "time_ms": 1684006089927, "event_type": "POINT_IN_TIME", "key": "eval_accuracy", "value": {0}, "metadata": {"file": "check_run_stop.py", "lineno": 411, "epoch_num": 16}}
```
This is line contains 'run_stop' string, but this is not a run_stop event, in which case 'run_stop' is the key.
=> Fix run stop check

mlperf_logging/mllog/examples/power/power_measurement.py
- When using the `--start-with-readings` flag the first power reading not being dropped and didn't appear in the final log
=> Fix Bug: Avoid dropping first reading

mlperf_logging/package_checker/package_checker.py, mlperf_logging/result_summarizer/config.yaml, mlperf_logging/result_summarizer/result_summarizer.py, mlperf_logging/system_desc_checker/system_desc_checker.py
=> Enforce and map availability

mlperf_logging/package_checker/package_checker.py
=> Add rcp-bypass granularity

mlperf_logging/rcp_checker/training_4.0.0/rcps_gnn.json, mlperf_logging/rcp_checker/training_4.0.0/rcps_llama2_70b_lora.json, mlperf_logging/rcp_checker/training_4.0.0/rcps_ssd.json, mlperf_logging/rcp_checker/training_4.0.0/rcps_stable_diffusion.json
Adding the following new RCPs for v4.0
gnn - GBS 262144
llama2_70b_lora - GBS 128
ssd - GBS 2560
stable_diffusion - GBS 384
=> [NVIDIA] Add new RCPs for v4.0

mlperf_logging/rcp_checker/rcp_checker.py
=> Calculate Stdev without olympic pruning

mlperf_logging/compliance_checker/README.md, mlperf_logging/compliance_checker/training_4.1.0/closed_common.yaml, mlperf_logging/compliance_checker/training_4.1.0/closed_llama2_70b_lora.yaml, mlperf_logging/rcp_checker/rcp_checker.py, mlperf_logging/result_summarizer/config.yaml
This PR is fixing minor issues (typos) that were created when adding 4.1.0 ruleset. Please create rc2 tag.
I'm removing [lora_alpha](https://github.com/mlcommons/logging/pull/383/files#diff-9d2c3affa7e0d39b372bd4fc106faaf05d660aabf6fa8006cf5dcbb49443596aL10-L13) because currently there is a duplication ([1](https://github.com/mlcommons/logging/blob/master/mlperf_logging/compliance_checker/training_4.1.0/closed_llama2_70b_lora.yaml#L11-L13), [2](https://github.com/mlcommons/logging/blob/master/mlperf_logging/compliance_checker/training_4.1.0/closed_llama2_70b_lora.yaml#L31-L33)).
=> Minor fixes for 4.1.0 submission

mlperf_logging/package_checker/package_checker.py, mlperf_logging/package_checker/seed_checker.py
The WG has discussed requiring logging the seeds for official submissions. This PRs contains the changes to reflect that:
- Check seeds are always logged
- Remove unnecessary warnings and outdated tests
- Update comments
Only merge if seed requirement is approved by the WG and changed in the policies/training_policies repositories
=> Check seeds are always logged

mlperf_logging/compliance_checker/training_4.1.0/common.yaml
=> Remove status check from compliance checker

mlperf_logging/compliance_checker/training_5.0.0/closed_common.yaml, mlperf_logging/compliance_checker/training_5.0.0/common.yaml, mlperf_logging/compliance_checker/training_5.0.0/open_common.yaml
There are a number of fields in the `results.txt` files that were made redundant (and therefor error prone and inconsistent) when we introduced the `systems/*.json` files in v1.0.
This PR removes the compliance checker checks for the `submission_org` and `submission_platform` fields from the training v5.0.0 compliance checker `common.yaml` file.
These two fields in the `result*.txt` files are redundant, and (other than their presence) are not used for anything or checked by any of the compliance or package checkers. They are difficult for many submitters to get correct in their submissions, and are often a source of confusion and/or extra work during the submission review period.
Historically, there were originally 4 fields:
1. `submission_platform` which is redundant with some …
=> remove redundant/extraneous submission_org and submission_platform fields from compliance checks before training v5.0
